import type { Product } from "./store-context"

export const products: Product[] = [
  {
    id: "1",
    name: "AXIS Drip Hoodie",
    price: 89.99,
    originalPrice: 120.00,
    image: "/images/products/hoodie-black.jpg",
    category: "Hoodies",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Negro", "Gris"],
    description: "Hoodie oversized con graficos de graffiti drip exclusivos de AXIS. Tela premium de algodon 100% con interior de felpa. Corte urbano con capucha doble y bolsillo canguro.",
    isFeatured: true,
    isNew: true,
  },
  {
    id: "2",
    name: "Urban Tag Tee",
    price: 45.99,
    image: "/images/products/tshirt-purple.jpg",
    category: "Camisetas",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Purpura", "Negro"],
    description: "Camiseta de corte oversized con estampado de tags urbanos. Algodon organico de alta calidad. Diseno exclusivo inspirado en el arte callejero.",
    isFeatured: true,
  },
  {
    id: "3",
    name: "Street Bomber Jacket",
    price: 159.99,
    originalPrice: 199.99,
    image: "/images/products/jacket-street.jpg",
    category: "Chamarras",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro", "Purpura"],
    description: "Chamarra bomber con acabados urbanos y detalles en purpura. Exterior resistente al agua con forro interior acolchado. Bolsillos con cierre y punos elasticos.",
    isFeatured: true,
    isNew: true,
  },
  {
    id: "4",
    name: "Cargo Street Pants",
    price: 79.99,
    image: "/images/products/cargo-pants.jpg",
    category: "Pantalones",
    sizes: ["28", "30", "32", "34", "36"],
    colors: ["Negro", "Gris Oscuro"],
    description: "Pantalones cargo con multiples bolsillos de estilo militar urbano. Tela resistente con elasticidad para mayor comodidad. Cintura ajustable con cordon.",
  },
  {
    id: "5",
    name: "Graffiti Classic Tee",
    price: 39.99,
    image: "/images/products/tshirt-white.jpg",
    category: "Camisetas",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blanco", "Negro"],
    description: "Camiseta clasica con estampado de graffiti art en el pecho. 100% algodon peinado de primera calidad. Cuello reforzado y costuras dobles.",
    isFeatured: true,
  },
  {
    id: "6",
    name: "AXIS Purple Reign Hoodie",
    price: 95.99,
    originalPrice: 130.00,
    image: "/images/products/hoodie-purple.jpg",
    category: "Hoodies",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Purpura", "Negro"],
    description: "Hoodie premium en purpura profundo con grafico de pintura drip en blanco. Tela de algodon francesa con acabado suave. Edicion limitada AXIS.",
    isNew: true,
  },
  {
    id: "7",
    name: "Street Crown Cap",
    price: 34.99,
    image: "/images/products/cap-black.jpg",
    category: "Accesorios",
    sizes: ["Unica"],
    colors: ["Negro", "Purpura"],
    description: "Gorra snapback con bordado de corona graffiti. Panel frontal estructurado con visera plana. Ajuste trasero de broche metalico.",
  },
  {
    id: "8",
    name: "Urban Mesh Shorts",
    price: 54.99,
    image: "/images/products/shorts-black.jpg",
    category: "Pantalones",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Negro", "Purpura"],
    description: "Shorts de malla con franja lateral en purpura. Cintura elastica con cordon interior. Bolsillos laterales con cierre. Perfecto para el streetwear de verano.",
  },
]

export const categories = ["Todos", "Camisetas", "Hoodies", "Chamarras", "Pantalones", "Accesorios"]
